pipeline {
    agent any
	environment {
    registry = "jajodiatushar/httpapplication"
    registryCredential = "dockerhub"
	}
    
	stages {
        stage('Build') {
            steps {
				echo "Building The Project Chat-Application"
				sh """
					chmod +x gradlew
                    ./gradlew build -x test	
				"""
				echo "Building Completed"
            }
        }
        stage('Test') {
            steps {
                echo "Testing The Project Chat-Application"
				sh """
					chmod +x gradlew
                    ./gradlew test
				
				"""
				echo "Testing Completed"
            }
        }
		stage('Static Code Analysis') {
            steps {
                echo "Static code analysis in sonarcloud.io"
				sh "gradlew sonarqube -Dsonar.projectKey=httpapplication -Dsonar.organization=jajodiatushar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a8db4e927077bc7374d41d0cb79669a21bde0023"
            }
        }
		
        stage('Deploy') {
            steps {
                echo "Deploying The Project Chat-Application"
				sh "docker build --no-cache -t 'httpapplication' -f .infra/docker/Dockerfile ."
            }
        }
		
		stage('publishing') {
            steps {
                echo "publishing the application to DockerHub"
				sh "docker login -u jajodiatushar -p abc123ABC!@#"
				sh "docker tag httpapplication:latest jajodiatushar/httpapplication:latest"
				sh "docker push jajodiatushar/httpapplication:latest"
            }
        }
    }
}