pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
				echo "Building The Project Chat-Application"
				sh """
					chmod +x gradlew
                    ./gradlew build -x test	
				"""
				echo "Building Completed"
            }
        }
        stage('Test') {
            steps {
                echo "Testing The Project Chat-Application"
				sh """
					chmod +x gradlew
                    ./gradlew test
				
				"""
				echo "Testing Completed"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying The Project Chat-Application"
				sh """
					chmod +x docker
					./docker build -t "chatapplication" -f .infra/docker/Dockerfile 
				"""
            }
        }
    }
}